title: zzz
frequency: 3
dirfilter:
- tmp
- .github
- .git
- public
- scripts
- assets
- vendor
- logs
ext:
- go
- html
enablerun: true
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - go generate internal/assets/conf/conf.go
  - go generate internal/assets/public/public.go
  - go mod tidy
  - go mod vendor
  after:
  - ps -ef|grep 'novelsearch service'| grep -v grep | awk '{print $2}' | xargs kill -9
  # brew install upx
  - upx -9 novelsearch
  - ./novelsearch service &
  exit:
  - ps -ef|grep 'novelsearch service'| grep -v grep | awk '{print $2}' | xargs kill -9 
link: https://github.com/midoks/zzz
